// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {appservice} from '../models';
import {scanner} from '../models';

export function ClearParse():Promise<void>;

export function ExportRules(arg1:config.RuleConfig):Promise<appservice.SavedFile>;

export function GetDefaultRules():Promise<config.RuleConfig>;

export function GetRules():Promise<config.RuleConfig>;

export function ImportRules():Promise<appservice.ImportRulesResult>;

export function IsRulesDirty():Promise<boolean>;

export function Parse(arg1:Array<scanner.MessageSource>):Promise<appservice.ParseResult>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveAs():Promise<appservice.SavedFile>;

export function SaveRules(arg1:config.RuleConfig):Promise<void>;

export function SaveToDownloads():Promise<appservice.SavedFile>;

export function ScanSources(arg1:Array<string>):Promise<appservice.ScanResult>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SetRulesDirty(arg1:boolean):Promise<void>;

export function TestRule(arg1:string,arg2:config.RuleConfig):Promise<appservice.SandboxResult>;

export function ValidateRules(arg1:config.RuleConfig):Promise<Array<appservice.ValidationError>>;
