// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearParse() {
  return window['go']['appservice']['Service']['ClearParse']();
}

export function ExportRules(arg1) {
  return window['go']['appservice']['Service']['ExportRules'](arg1);
}

export function GetDefaultRules() {
  return window['go']['appservice']['Service']['GetDefaultRules']();
}

export function GetRules() {
  return window['go']['appservice']['Service']['GetRules']();
}

export function ImportRules() {
  return window['go']['appservice']['Service']['ImportRules']();
}

export function IsRulesDirty() {
  return window['go']['appservice']['Service']['IsRulesDirty']();
}

export function Parse(arg1) {
  return window['go']['appservice']['Service']['Parse'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['appservice']['Service']['RevealFile'](arg1);
}

export function SaveAs() {
  return window['go']['appservice']['Service']['SaveAs']();
}

export function SaveRules(arg1) {
  return window['go']['appservice']['Service']['SaveRules'](arg1);
}

export function SaveToDownloads() {
  return window['go']['appservice']['Service']['SaveToDownloads']();
}

export function ScanSources(arg1) {
  return window['go']['appservice']['Service']['ScanSources'](arg1);
}

export function SelectFiles() {
  return window['go']['appservice']['Service']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['appservice']['Service']['SelectFolder']();
}

export function SetRulesDirty(arg1) {
  return window['go']['appservice']['Service']['SetRulesDirty'](arg1);
}

export function TestRule(arg1, arg2) {
  return window['go']['appservice']['Service']['TestRule'](arg1, arg2);
}

export function ValidateRules(arg1) {
  return window['go']['appservice']['Service']['ValidateRules'](arg1);
}
